services:
  - type: web
    name: schedule-service
    env: python
    plan: free
    region: frankfurt
    buildCommand: ""
    startCommand: "python main_combined.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: student_schedule_db
          property: connectionString

databases:
  - name: student_schedule_db
    plan: free
