services:
  - type: web
    name: nmadur-api
    env: docker           # docker environment
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile.api   # <- bu qator muhim
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student_schedule_db
          property: connectionString

  - type: web
    name: nmadur-bot
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile.bot   # <- bot uchun Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
