services:
  - type: web
    name: nmadur-api
    env: docker
    dockerfilePath: Dockerfile.api
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student_schedule_db
          property: connectionString

  - type: web
    name: nmadur-bot
    env: docker
    dockerfilePath: Dockerfile.bot
    plan: free
    region: frankfurt
    envVars:
      - key: BOT_TOKEN
        sync: false
