services:
  - type: web
    name: nmadur-api
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    startCommand: "uvicorn nmadur_api:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student_schedule_db
          property: connectionString
