services:
  - type: web
    name: nmadur-api
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: nmadur_api/Dockerfile
    startCommand: "uvicorn nmadur_api:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student_schedule_db
          property: connectionString
      - key: GOOGLE_CREDS_JSON
        sync: false

databases:
  - name: student_schedule_db
    plan: free
